### PR TITLE
Edits to support fluorescence data plots

### PR DESCRIPTION
**Pull request by samwebb10**
So this is my first try with Github, so hopefully I did this correctly...

I made some edits which included adding a few extra SSRL beam lines (and putting them in the SSRL name convention) and a new spectrum  mode - fluorescence, unitstep.
Supports plotting of fluorescence data, and the incorporation of the fluorescence data into the data base.  The unit step (based on a biassed SIXPACK point of view) is used if unit step normalized data is uploaded. This will also pass the pre-edge part of the spectrum view.

Cheers all!
Sam

### CODE REVIEW

**Comment by newville** [comment]
@samwebb10  @bruceravel Thanks!  That is definitely the right workflow, and fixing/adding more SSRL beamlines and plotting for fluorescence data is great.   

I don't quite understand "samnorm" or "fluorescence, unit step".  The other "modes" describe how the data was collected, not processed.   The general idea is to have something like "raw" mu(E) stored in the files that could be processed by anyone and any program.   I think it would be OK to add a normalized channel too, but I'm not sure we want to have lots of different types of normalized data, and I think we'd definitely want to have "raw mufluor" as well.

**Comment by samwebb10** [comment]
Thanks! @newville @bruceravel 
I agree with the mode concept you state in principle, but for my own use, I ran into (1) I have bunch of old data where I only have a normalized unit step mu and have no idea where the raw data is anymore, and (2) I have a ton of S edge data where my data range is much smaller, and I've needed to do a lot of adjusting in the pre-edge to get a good step.  Thus, the unit step.  Its not a preferred data type, but its one that I needed. I don't think (of course I could be wrong) that there's a lot of other necessary data types past that.  I did add a catch for the mufluor type (similar to the mutrans that exists).
The samnorm is again more of a bias that I have for my current version of SIXPACK which outputs in the column in mu data historically as "samnorm".  Granted, that really probably should change too… but its what i added to make things work for me faster than a lot of extra hand editing.  I'm not tied to it, and actually, as I type this, would be open to fixing it at the source (in SIXPACK).

**Comment by newville** [comment]
@samwebb10  I understand having data that might be good but that you don't have the full raw data set.  I  think it is OK to have normalized data, but why not just call it mufluor?   Perhaps we should set aside part of the XDI namespace for describing processing steps.  

But, for the public libraries and XDI files, we're trying to make sure that someone far away (distance or time) will be able to use these data, and sticking to clearly defined terms seems like one way to do that.

For "tender" energy data like S K edge, I agree that the pre-edge / normalization parameters need different defaults.  These could be adjusted with energy, or maybe specified in the XDI metadata.  It might make sense to allow these to be adjusted in the web app, too.

**Comment by samwebb10** [comment]
@newville I agree. And i did add a mufluor entry for the "general library" for just that reason to be more general for a broader group.  The samnorm is the exact same, just what I used in the old days in SIXPACK and have not made adjustments. Like I said, I am feeling the need to update my old thinking to make it more general.  Is the adjustment to the XASDataLibrary something that I should resubmit in a request then, or something that I/you edit in the current pull request? (Git noob question)

I think it'd be nice to have more flexible parameters for the web app, but on the other hand, the app is probably most used for browsing data, not necessarily real data reduction.  Probably don't need to turn the web app into "Larch Lite" or the similar.

For the data processing steps, in the XDI namespace, for my two cents, I think the XDI format should leave it flexible -- not everyone will use the same names/concepts even -- outside of Athena and SIXPACK which use the same IFEFFIT/Larch parameters.  I've gone to recording all my SIXPACK parameters in my XDI file in a SIXPACK.parameter group, but I doubt such a style needs to be formalized specifically.

**Comment by newville** [comment]
@samwebb10   @bruceravel   The normal workflow for Pull Requests is that you can just make changes and do a "git push" to your fork, and the Pull Request will be automatically updated.    But if your unsure, just let me know and I'll merge as is and we can go from there.

I think it's OK to have non-standard-name arrays (like "samnorm") in a file, just that the files should also have some of the standard-named arrays too....

I've deliberately avoided importing analysis code from Larch.   Somewhat related, it might be appropriate to work on pre-edge subtraction and normalization routines!    I think it's nice for the web app to have some of these capabilities, but I don't think it should dominate the effort -- the idea is really to provide a browsable store of data, not do any analysis. 

And I agree that it's a real challenge to try to put processing "parameters" in a text file without implicitly expecting an analysis algorithm.    Anything that is more complicated than "maximum of first derivative" or "linear regression" quickly becomes a can of worms.   But we could say something like "the pre-edge range is 2450 to 2465 eV and the normalization range in 2550 to 2700 eV".

**Comment by newville** [comment]
thanks!

**Pull request merged**
