### PR TITLE
Facilities and beamlines metadata

### PR DESCRIPTION
**Pull request by bruceravel**
So, I was kind of unsatisfied by the rather meager offerings starting at
   https://github.com/XraySpectroscopy/XASDataLibrary/blob/master/xasdb/creator.py#L60

I decided that the facilities and beamlines metadata should get solved once and for all.

To flesh out the facilities metadata, I sent email to the contact link at lightsources.org.  A couple of days later, I was sent the `lightsources.org.json` file, which is very helpful, but kind of a mess.  So I wrote a one-off script for sanitizing the content.  The biggest problem was that the contact information was inconsistently structured and shot through with html tags.  The `synchrotrons.json` file contains the sanitized data from the lightsources.org file.  I also wrote out `fels.json` -- who knows? someone might measure something XAS-y at an FEL facility...

To flesh out the beamlines metadata, I wrote a one-off script to scrape data from the tables at the IUCr compendium that Federico Boscherini originally compiled and which is now maintained by Giuliana Aquilanti and Masao Tabuchi.  This, too, was a mess of inconsistencies and poorly structured HTML.  Eventually, I was able to write out fairly consistent entries for every beamline into the files `Americas.json`, `Asia.json`, and `Europe.json`.

The next challenge was that facility nomenclature was not consistent.  So I made a file called `names.json` and used it to synchronize facility nomenclature between the `synchrotrons.json` file and the three regional json beamline files.  I settled on the nomenclature used by lightsources.org.

This is just a start, but I want to make this PR so we can begin discussing how to format this stuff in a way that is as useful as possible for XASDataLibrary.  In particular, the beamline entries need more metadata entries, such as `Facility.xray_source` and possibly things in the `Beamline` and `Mono` namespaces (to use XDI nomenclature...).

### CODE REVIEW

**Comment by newville** [comment]
Hmm, OK, I'm not sure about several parts of this.

How should this data get used?  What goes into the database? I see several
json files, but I don't really know what to do with them.

Like, what did you find unsatisfying by the "meager offerings" in the
existing faciities table?  I'm not really sure that we need a complete list
of facilities, or need all the data contained here for any of the
facilities.  So, what info _should_ be given for the facilities and
beamlines?

As the idea is spectral libraries, it seems the principal question should
be "what is needed to understand a spectrum or group of related spectra"?
It is very useful to know the beamline at which a spectrum was collected
at.  It might even be called "imperative" to have this, but I'm reluctant
to start requiring metadata.  Anyway, being able to sensibly record the
beamline seems important.  To that end, a table of beamlines seems useful,
so that "SSRL 4-3" is spelled the same for all spectra collected there.
Since there are many beamlines at most facilities, a similar table of
facilities is useful, just so that SSRL is spelled the same.  But I don't
know what is really needed other than beamline name and facility name, and
the corresponding pointers in the tables.  We definitely want to allow
"Show me all the Cr K edge spectra collected at Photon Factory and the SLS
SuperXAS beamline", and the table layout makes that easy.  Do we need a fax
number?

A separate question would be how should this data be maintained?

My preference would be to focus on XAFS spectra an keeping the database and
project as simple as possible - it's enough work, and it's not really clear
to me how it will evolve.  I was taking the approach that anyone would be
able to look up an existing facility or add a facility or beamline as
needed.  That seems easier to maintain to me, and doesn't require
centralized authority or expertise.  If someone wanted to use this database
code for EELS data from an electron probe or for spectra from a lab X-ray
source, why not?

--Matt

**Comment by bruceravel** [comment]
I don't actually know the answer to very many of your questions and I completely agree that the current state of those little JSON files is unclear and preliminary, at best.

You have a small handful of the world's synchrotrons hardwired into the code and an even smaller number of its XAS beamlines.  That seemed weird to me, so I was wondering: why hardwire any of them?  Or, why not try to capture all of them -- it's a few dozen facilities and a couple hundred beamlines ... not that many.

Of course we don't need a fax number.  I was just trying to make sense of what was in the file I was provided by the fellow who manages lightsources.org.  

Part of that information was an address for each synchrotron.  For each synchrotron in the hard-wired list, there is a completely arbitrary string which sort of geolocates the synchrotron.  `'Synchrotron SOLEIL, GIF-sur-YVETTE, France'` is a pretty sensible, minimalist statement of location.  `'Karlsruhe, KIT, Germany'` might also make but it is backwards from several other entries in that is places the city name ahead of the institution name.  If you say (and you appear to be saying that) that geolocation isn't really meaningful for searches of XAS data, then why is `facilities` that particular list of lists and not, say, a dictionary for which the keys are the common acronym and the values the fully spelled-out facility name.  Or why not have the "notes" entry in the table be the facility URL rather than a vague, geolocation string?

> So, what info _should_ be given for the facilities and beamlines?

I thought this was the question I was trying to ask.  Rather than simply opening an issue, I thought I would actually do something and see what was available using existing resources.  Maybe a PR wasn't quite the right venue for this discussion, but they are easy enough to close and ignore....

The beamline resource at IUCr is certainly insufficient -- energy range and typical spot size are not especially useful information in this context.  `Facility.xray_source` and, I guess, stuff from `Beamline.` and `Mono.` would actually be useful.

**Comment by newville** [comment]
On Fri, May 8, 2015 at 10:41 AM, Bruce Ravel notifications@github.com
wrote:

> I don't actually know the answer to very many of your questions and I
> completely agree that the current state of those little JSON files is
> unclear and preliminary, at best.
> 
> You have a small handful of the world's synchrotrons hardwired into the
> code and an even smaller number of its XAS beamlines. That seemed weird to
> me, so I was wondering: why hardwire any of them? Or, why not try to
> capture all of them -- it's a few dozen facilities and a couple hundred
> beamlines ... not that many.
> 
> I'd be fine with including all the facilities and beamlines we know about,
> and to try to normalize the data.  Perhaps a facility should have "City",
> "Country", and "Institution" or "Parent Laboratory" or whatever.  I would
> not want to go overboard.

I'd also be OK with starting with an empty list of beamlines and facilities
too, it was just that I know I'm going to add some data, so wanted to have
a feel for what went into the beamline and facility table.

> Of course we don't need a fax number. I was just trying to make sense of
> what was in the file I was provided by the fellow who manages
> lightsources.org.
> 
> Part of that information was an address for each synchrotron. For each
> synchrotron in the hard-wired list, there is a completely arbitrary string
> which sort of geolocates the synchrotron. 'Synchrotron SOLEIL,
> GIF-sur-YVETTE, France' is a pretty sensible, minimalist statement of
> location. 'Karlsruhe, KIT, Germany' might also make but it is backwards
> from several other entries in that is places the city name ahead of the
> institution name. If you say (and you appear to be saying that) that
> geolocation isn't really meaningful for searches of XAS data, then why is
> facilities that particular list of lists and not, say, a dictionary for
> which the keys are the common acronym and the values the fully spelled-out
> facility name. Or why not have the "notes" entry in the table be the
> facility URL rather than a vague, geolocation string?

I think the concern for such data is that it could easily become
out-of-date.    I suppose name of city/country/lab could too, but they
change less often, and they're often used as part of the identification
(someone might say data was collected at "PSI" or "Brookhaven").    So,
perhaps we can take the approach that we include information used to
identify a beamline or facility.

 So, what info _should_ be given for the facilities and beamlines?

> I thought this was the question I was trying to ask. Rather than simply
> opening an issue, I thought I would actually do something and see what was
> available using existing resources. Maybe a PR wasn't quite the right venue
> for this discussion, but they are easy enough to close and ignore....
> 
> I think a PR sort of says "here are some files to add / change that solve a
> problem".   That's OK, I'm just trying to understand what the problem is
> --- some but not all facilities are listed, right?

The beamline resource at IUCr is certainly insufficient -- energy range and

> typical spot size are not especially useful information in this context.
> Facility.xray_source and, I guess, stuff from Beamline. and Mono. would
> actually be useful.
> 
> I think 'xray_source' is useful, but I also think it sort of has to go with
> beamline, not facility.  Having mono d-spacing is definitely useful.  I'd
> say it's  "almost required", much like beamline name -- a spectrum might be
> useable without this, but is made more useful by having these fields.

I'm not sure about anything else.  At this point, I'd say let's not worry
too much about things we are not certain we need.  There are enough pieces
missing that we know we do need.

  --Matt

**Comment by newville** [comment]
OK, this is 5 years old, but I don't know why it never got merged...  Merging now and will try to manage with keeping it up-to-date.

**Pull request merged**
